# Generated by Django 4.2.7 on 2026-05-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentbill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcategory'),
        ),
    ]
