# Generated by Django 4.2.7 on 2026-05-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_treasurer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'siswa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classes.school'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'academic_year', 'name')},
        ),
    ]
