# Generated by Django 4.2.7 on 2026-05-10 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('absen', 'Absen'), ('sakit', 'Sakit'), ('izin', 'Izin')], default='hadir', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendances',
                'ordering': ['-date'],
            },
        ),
    ]
